import React from 'react';
import * as Button from '@/components/ui/button';
import * as Badge from '@/components/ui/badge';
import PageHeader from '@/components/page-header';
import StatsStrip from '@/components/stats-strip';
import { RiReceiptLine, RiRefreshLine, RiArrowRightLine, RiAlertLine } from '@remixicon/react';

interface EwayStatProps {
  label: string;
  value: number | string;
  color?: 'blue' | 'green' | 'orange' | 'red' | 'purple' | 'default';
}

const CARD_TONES = {
  default: { bg: 'bg-bg-weak-50 border-stroke-soft-200', value: 'text-text-strong-950', label: 'text-text-sub-600' },
  blue: { bg: 'bg-information-lighter border-information-light', value: 'text-information-dark', label: 'text-information-base' },
  green: { bg: 'bg-success-lighter border-success-light', value: 'text-success-dark', label: 'text-success-base' },
  orange: { bg: 'bg-warning-lighter border-warning-light', value: 'text-warning-dark', label: 'text-warning-base' },
  red: { bg: 'bg-error-lighter border-error-light', value: 'text-error-dark', label: 'text-error-base' },
  purple: { bg: 'bg-feature-lighter border-feature-light', value: 'text-feature-dark', label: 'text-feature-base' },
};

function EwayStat({ label, value, color = 'default' }: EwayStatProps) {
  const tone = CARD_TONES[color];
  return (
    <div className={`flex flex-col items-center justify-center rounded-lg border px-4 py-5 text-center ${tone.bg}`}>
      <span className={`text-title-h5 font-bold tabular-nums sm:text-title-h4 ${tone.value}`}>{value}</span>
      <span className={`mt-1 text-center text-paragraph-xs font-medium ${tone.label}`}>{label}</span>
    </div>
  );
}

export default function EwayBillPage() {
  return (
    <div className="space-y-6">
      <PageHeader
        icon={RiReceiptLine}
        iconColor="bg-away-lighter text-away-base"
        title="EwayBill Dashboard"
        subtitle="API integration with government EwayBill system"
        breadcrumbs={[{ label: 'EwayBill' }, { label: 'Eway Dashboard' }]}
      >
        <Button.Root variant="neutral" mode="stroke" size="small">
          <Button.Icon as={RiRefreshLine} />
          FetchEwayBill
          <span className="ml-1 text-paragraph-xs text-text-sub-600">25-04-2026</span>
        </Button.Root>
      </PageHeader>

      <StatsStrip stats={[
        { label: 'Total EWBs', value: '191,780', trend: 5.2, trendLabel: 'this month' },
        { label: 'Generated By Me', value: 63, trend: 8, trendLabel: 'vs last week' },
        { label: 'Archived', value: 180, trend: -2.1, trendLabel: 'vs last week' },
        { label: 'Expiring Today', value: 25, trend: -15, trendLabel: 'vs yesterday' },
      ]} />

      {/* Alert banner */}
      <div className="flex flex-col gap-3 rounded-xl border border-warning-light bg-warning-lighter px-4 py-4 sm:flex-row sm:items-center sm:gap-4 sm:px-5">
        <div className="flex flex-1 items-start gap-3 sm:items-center">
          <div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-warning-light">
            <RiAlertLine size={18} className="text-warning-dark" />
          </div>
          <div className="min-w-0 flex-1">
            <p className="text-label-sm text-warning-dark">0 Actionable EWBs assigned for last 48 hrs</p>
            <p className="text-paragraph-sm text-warning-base mt-0.5">Assigned Eway Bill To Us. All Actionable EWB&apos;s are up to date.</p>
          </div>
        </div>
        <Badge.Root size="medium" variant="light" color="orange" className="ml-[52px] self-start sm:ml-0 sm:self-auto">0 Pending</Badge.Root>
      </div>

      {/* Main stats grid */}
      <div className="rounded-xl border border-stroke-soft-200 bg-bg-white-0 p-4 shadow-regular-xs space-y-5 sm:p-6">
        <div>
          <p className="text-subheading-xs uppercase tracking-wider text-text-sub-600 mb-3">My Eway Bill (191,780)</p>
          <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
            <EwayStat label="Assign For Transport" value="191,780" />
            <EwayStat label="Generated By Me" value={63} color="green" />
            <EwayStat label="Generated By Others" value={8} color="blue" />
            <EwayStat label="Archived EWBs" value={180} color="purple" />
          </div>
        </div>

        <div className="grid grid-cols-1 gap-x-3 gap-y-5 lg:grid-cols-2">
          <div>
            <p className="text-subheading-xs uppercase tracking-wider text-text-sub-600 mb-3">Part B Details (589)</p>
            <div className="grid grid-cols-2 gap-3">
              <EwayStat label="Updated Part B" value={339} color="green" />
              <EwayStat label="Not Updated Part B" value={250} color="orange" />
            </div>
          </div>
          <div>
            <p className="text-subheading-xs uppercase tracking-wider text-text-sub-600 mb-3">Transporter Details (1)</p>
            <div className="grid grid-cols-2 gap-3">
              <EwayStat label="Assign Transporter" value={1} color="blue" />
              <EwayStat label="Receive Transporter" value={0} />
            </div>
          </div>
        </div>
      </div>

      {/* Expiry tracking */}
      <div className="rounded-xl border border-stroke-soft-200 bg-bg-white-0 p-4 shadow-regular-xs sm:p-6">
        <p className="text-subheading-xs uppercase tracking-wider text-text-sub-600 mb-4">Expiry Tracking</p>
        <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
          {[
            { label: 'Expired Yesterday', value: 19, bg: 'bg-error-lighter border-error-light', text: 'text-error-dark', sub: 'text-error-base' },
            { label: 'Expiring Today', value: 25, bg: 'bg-warning-lighter border-warning-light', text: 'text-warning-dark', sub: 'text-warning-base' },
            { label: 'Only Part A EWBs', value: '14,308', bg: 'bg-information-lighter border-information-light', text: 'text-information-dark', sub: 'text-information-base' },
            { label: 'Pending over 12 days', value: 223, bg: 'bg-feature-lighter border-feature-light', text: 'text-feature-dark', sub: 'text-feature-base' },
          ].map(s => (
            <div key={s.label} className={`rounded-lg border ${s.bg} px-4 py-4 text-center`}>
              <p className={`text-title-h5 font-bold tabular-nums sm:text-title-h4 ${s.text}`}>{s.value}</p>
              <p className={`text-paragraph-xs mt-1 ${s.sub}`}>{s.label}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Quick access */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
        {[
          { label: 'Local EWBs', desc: 'Distance less than 200kms' },
          { label: 'Docket With EWBs', desc: 'All assigned EWBs' },
        ].map(c => (
          <button key={c.label} className="flex items-center justify-between rounded-xl border border-stroke-soft-200 bg-bg-white-0 px-5 py-4 shadow-regular-xs transition hover:border-stroke-sub-300 hover:bg-bg-weak-50 text-left">
            <div>
              <p className="text-label-sm text-text-strong-950">{c.label}</p>
              <p className="text-paragraph-sm text-text-sub-600 mt-0.5">{c.desc}</p>
            </div>
            <RiArrowRightLine size={16} className="text-text-disabled-300 shrink-0" />
          </button>
        ))}
      </div>
    </div>
  );
}
